import type { QuoterConfig } from "../types"

export const tuanyiConfig: QuoterConfig = {
  id: "group-accident-quoter",
  name: "团体意外险报价器",
  title: "团体意外险报价器",
  description: "用于计算团体意外险保费",
  fields: [
    {
      id: "companyName",
      name: "投保企业名称",
      label: "投保企业名称",
      type: "text",
      required: true,
      defaultValue: "",
    },
    {
      id: "occupation",
      name: "职业类别",
      label: "职业类别",
      type: "select",
      required: true,
      options: [
        { label: "一类", value: "class1" },
        { label: "二类", value: "class2" },
        { label: "三类", value: "class3" },
        { label: "四类", value: "class4" },
        { label: "五类", value: "class5" },
        { label: "六类", value: "class6" },
      ],
      defaultValue: "class2",
    },
    {
      id: "peopleCount",
      name: "投保人数",
      label: "投保人数",
      type: "number",
      required: true,
      min: 10,
      max: 100000,
      suffix: "人",
      defaultValue: 10,
      tooltip: "团体投保最少10人",
    },
    {
      id: "workType",
      name: "工种选择",
      label: "工种选择",
      type: "select",
      required: true,
      options: [
        { label: "正常工种", value: "normal" },
        { label: "正常工种（人力公司投保）", value: "hr" },
        { label: "保安、保洁", value: "security" },
        { label: "涉高空作业", value: "height" },
        { label: "涉特种作业", value: "special" },
      ],
      defaultValue: "normal",
    },
    {
      id: "accidentAmount",
      name: "意外身故伤残保额",
      label: "意外身故/伤残保额",
      type: "number",
      required: true,
      min: 1,
      max: 100,
      suffix: "万元",
      defaultValue: 60,
      tooltip: "五类、六类职业不超过60万元；四类职业不超过80万元；其他职业不超过100万元",
    },
    {
      id: "medicalAmount",
      name: "附加意外伤害医疗保额",
      label: "附加意外伤害医疗保额",
      type: "number",
      required: true,
      min: 0,
      max: 10,
      suffix: "万元",
      defaultValue: 5,
    },
    {
      id: "hospitalAllowance",
      name: "住院津贴",
      label: "住院津贴",
      type: "number",
      required: false,
      min: 0,
      max: 300,
      suffix: "元/天",
      defaultValue: 100,
      tooltip: "不能超过300元/天",
    },
    {
      id: "medicalRatio",
      name: "意外医疗扣除赔付比例",
      label: "意外医疗扣除赔付比例",
      type: "select",
      required: true,
      options: [
        { label: "意外医疗扣除100元后80%比例赔付", value: 80 },
        { label: "意外医疗扣除100元后90%比例赔付", value: 90 },
        { label: "意外医疗扣除100元后100%比例赔付", value: 100 },
      ],
      defaultValue: 80,
    },
    {
      id: "hospitalDays",
      name: "住院津贴免赔天数",
      label: "住院津贴免赔天数",
      type: "select",
      required: true,
      options: [
        { label: "免赔0天", value: 0 },
        { label: "免赔3天", value: 3 },
      ],
      defaultValue: 3,
    },
    {
      id: "insuranceDays",
      name: "投保天数",
      label: "投保天数",
      type: "number",
      required: true,
      min: 1,
      max: 365,
      suffix: "天",
      defaultValue: 365,
      tooltip: "不能超过365天",
    },
    {
      id: "suddenDeathAmount",
      name: "猝死保额",
      label: "猝死保额",
      type: "select",
      required: true,
      options: [
        { label: "猝死保额0万元", value: 0 },
        { label: "猝死保额10万元", value: 10 },
        { label: "猝死保额20万元", value: 20 },
        { label: "猝死保额30万元", value: 30 },
        { label: "猝死保额40万元", value: 40 },
        { label: "猝死保额50万元", value: 50 },
        { label: "猝死保额同主险", value: -1 },
      ],
      defaultValue: 0,
    },
  ],
  coefficientTables: [
    {
      id: "occupationCoef",
      name: "职业类别系数表（团意）",
      description: "根据职业类别确定各项系数",
      rowKeyName: "职业类别",
      colKeyName: "系数类型",
      data: {
        class1: {
          固定系数: 1.365,
          身故占比: 0.8,
          伤残占比: 0.2,
          医疗系数: 4.373,
          住院津贴系数: 0.0181,
          住院津贴系数折扣: 0.5,
          猝死系数: 0.6,
          人数系数: 1,
        },
        class2: {
          固定系数: 1.638,
          身故占比: 0.8,
          伤残占比: 0.2,
          医疗系数: 5.247,
          住院津贴系数: 0.0266,
          住院津贴系数折扣: 0.5,
          猝死系数: 0.6,
          人数系数: 1,
        },
        class3: {
          固定系数: 2.531,
          身故占比: 0.7,
          伤残占比: 0.3,
          医疗系数: 8.752,
          住院津贴系数: 0.0388,
          住院津贴系数折扣: 0.5,
          猝死系数: 0.6,
          人数系数: 1.25,
        },
        class4: {
          固定系数: 4.159,
          身故占比: 0.6,
          伤残占比: 0.4,
          医疗系数: 14.597,
          住院津贴系数: 0.0598,
          住院津贴系数折扣: 0.5,
          猝死系数: 0.6,
          人数系数: 1.25,
        },
        class5: {
          固定系数: 6.833,
          身故占比: 0.5,
          伤残占比: 0.5,
          医疗系数: 20.765,
          住院津贴系数: 0.0775,
          住院津贴系数折扣: 0.5,
          猝死系数: 0.6,
          人数系数: 1.25,
        },
        class6: {
          固定系数: 10.331,
          身故占比: 0.5,
          伤残占比: 0.5,
          医疗系数: 29.013,
          住院津贴系数: 0.0903,
          住院津贴系数折扣: 0.5,
          猝死系数: 0.6,
          人数系数: 1.25,
        },
      },
    },
    {
      id: "medicalRatioCoef",
      name: "医疗赔付比例系数",
      description: "根据赔付比例确定系数",
      rowKeyName: "比例",
      colKeyName: "系数",
      data: {
        "80": { 系数: 1 },
        "90": { 系数: 1.2 },
        "100": { 系数: 1.4 },
      },
    },
    {
      id: "hospitalDaysCoef",
      name: "住院津贴免赔天数系数",
      description: "根据免赔天数确定系数",
      rowKeyName: "免赔天数",
      colKeyName: "系数",
      data: {
        "0": { 系数: 1.5 },
        "3": { 系数: 1 },
      },
    },
    {
      id: "insuranceDaysCoef",
      name: "投保天数系数表",
      description: "根据投保天数确定系数",
      rowKeyName: "天数区间",
      colKeyName: "系数",
      data: {
        "1": { 系数: 0.1 },
        "31": { 系数: 0.2 },
        "61": { 系数: 0.3 },
        "91": { 系数: 0.4 },
        "121": { 系数: 0.5 },
        "151": { 系数: 0.6 },
        "181": { 系数: 0.7 },
        "211": { 系数: 0.8 },
        "241": { 系数: 0.85 },
        "271": { 系数: 0.9 },
        "301": { 系数: 0.95 },
        "331": { 系数: 1 },
      },
    },
    {
      id: "workTypeCoef",
      name: "工种系数表",
      description: "根据工种类型确定系数",
      rowKeyName: "工种",
      colKeyName: "系数",
      data: {
        normal: { 系数: 1 },
        hr: { 系数: 1 },
        security: { 系数: 5 },
        height: { 系数: 1 },
        special: { 系数: 1 },
      },
    },
  ],
  formulas: [
    {
      id: "deathPremium",
      name: "身故保费",
      description: "意外身故保额 × 固定系数 × 身故占比",
      expression: "ROUND($accidentAmount * LOOKUP(occupationCoef, $occupation, '固定系数') * LOOKUP(occupationCoef, $occupation, '身故占比'), 2)",
      dependencies: ["accidentAmount", "occupation"],
      showInResult: false,
      unit: "元",
    },
    {
      id: "disabilityPremium",
      name: "伤残保费",
      description: "意外伤残保额 × 固定系数 × 伤残占比",
      expression: "ROUND($accidentAmount * LOOKUP(occupationCoef, $occupation, '固定系数') * LOOKUP(occupationCoef, $occupation, '伤残占比'), 2)",
      dependencies: ["accidentAmount", "occupation"],
      showInResult: false,
      unit: "元",
    },
    {
      id: "medicalDiscountCoef",
      name: "医疗折扣系数",
      description: "根据医疗保额计算折扣系数",
      expression: "IF($medicalAmount > 8, 4.9 / $medicalAmount + 0.2, IF($medicalAmount > 7, 4.2 / $medicalAmount + 0.3, IF($medicalAmount > 6, 2.7 / $medicalAmount + 0.5, IF($medicalAmount > 5, 1.5 / $medicalAmount + 0.7, 1))))",
      dependencies: ["medicalAmount"],
      showInResult: false,
      unit: "",
    },
    {
      id: "medicalPremium",
      name: "医疗保费",
      description: "医疗保额 × 医疗系数 × 医疗折扣系数 × 赔付比例系数",
      expression: "ROUND($medicalAmount * LOOKUP(occupationCoef, $occupation, '医疗系数') * @medicalDiscountCoef * LOOKUP(medicalRatioCoef, $medicalRatio, '系数'), 2)",
      dependencies: ["medicalAmount", "occupation", "medicalRatio", "medicalDiscountCoef"],
      showInResult: false,
      unit: "元",
    },
    {
      id: "hospitalPremium",
      name: "住院津贴保费",
      description: "住院津贴 × 住院津贴系数 × 住院津贴系数折扣 × 免赔天数系数",
      expression: "ROUND($hospitalAllowance * LOOKUP(occupationCoef, $occupation, '住院津贴系数') * LOOKUP(occupationCoef, $occupation, '住院津贴系数折扣') * LOOKUP(hospitalDaysCoef, $hospitalDays, '系数'), 2)",
      dependencies: ["hospitalAllowance", "occupation", "hospitalDays"],
      showInResult: false,
      unit: "元",
    },
    {
      id: "suddenDeathCoverage",
      name: "猝死保额",
      description: "根据选择确定猝死保额（-1表示同主险）",
      expression: "IF($suddenDeathAmount == -1, $accidentAmount, $suddenDeathAmount)",
      dependencies: ["suddenDeathAmount", "accidentAmount"],
      showInResult: false,
      unit: "万元",
    },
    {
      id: "suddenDeathPremium",
      name: "猝死保费",
      description: "猝死保额 × 猝死系数 × 工种系数",
      expression: "ROUND(@suddenDeathCoverage * LOOKUP(occupationCoef, $occupation, '猝死系数') * LOOKUP(occupationCoef, $occupation, '猝死系数') * LOOKUP(workTypeCoef, $workType, '系数'), 2)",
      dependencies: ["suddenDeathCoverage", "occupation", "workType"],
      showInResult: false,
      unit: "元",
    },
    {
      id: "insuranceDaysCoef",
      name: "投保天数系数",
      description: "根据投保天数查询对应系数",
      expression: "IF($insuranceDays >= 331, 1, IF($insuranceDays >= 301, 0.95, IF($insuranceDays >= 271, 0.9, IF($insuranceDays >= 241, 0.85, IF($insuranceDays >= 211, 0.8, IF($insuranceDays >= 181, 0.7, IF($insuranceDays >= 151, 0.6, IF($insuranceDays >= 121, 0.5, IF($insuranceDays >= 91, 0.4, IF($insuranceDays >= 61, 0.3, IF($insuranceDays >= 31, 0.2, 0.1)))))))))))",
      dependencies: ["insuranceDays"],
      showInResult: false,
      unit: "",
    },
    {
      id: "riskPremiumTotal",
      name: "风险保费合计",
      description: "所有风险保费之和",
      expression: "ROUND(@deathPremium + @disabilityPremium + @medicalPremium + @hospitalPremium + @suddenDeathPremium, 2)",
      dependencies: ["deathPremium", "disabilityPremium", "medicalPremium", "hospitalPremium", "suddenDeathPremium"],
      showInResult: false,
      unit: "元",
    },
    {
      id: "baseMainPremium",
      name: "主险基准保费",
      description: "（风险保费合计 / 0.6）× 投保天数系数",
      expression: "ROUND((@riskPremiumTotal / 0.6) * @insuranceDaysCoef, 2)",
      dependencies: ["riskPremiumTotal", "insuranceDaysCoef"],
      showInResult: false,
      unit: "元",
    },
    {
      id: "peopleCountCoef",
      name: "人数系数",
      description: "根据投保人数确定系数",
      expression: "IF($peopleCount < 20, 1.2, IF($peopleCount <= 100, 1, 0.8))",
      dependencies: ["peopleCount"],
      showInResult: false,
      unit: "",
    },
    {
      id: "mainPremiumPerPerson",
      name: "主险保费（每人）",
      description: "基准保费 × 职业人数系数 × 人数系数 × 1.25",
      expression: "ROUND(@baseMainPremium * LOOKUP(occupationCoef, $occupation, '人数系数') * @peopleCountCoef * 1.25, 2)",
      dependencies: ["baseMainPremium", "occupation", "peopleCountCoef"],
      showInResult: true,
      unit: "元",
    },
    {
      id: "totalPremium",
      name: "总保费",
      description: "主险保费（每人）× 投保人数",
      expression: "ROUND(@mainPremiumPerPerson * $peopleCount, 2)",
      dependencies: ["mainPremiumPerPerson", "peopleCount"],
      showInResult: true,
      unit: "元",
    },
  ],
  sections: [
    {
      id: "basic",
      title: "基本信息",
      fieldIds: ["companyName", "occupation", "peopleCount", "workType"],
      collapsible: false,
    },
    {
      id: "coverage",
      title: "保障信息",
      fieldIds: ["accidentAmount", "medicalAmount", "hospitalAllowance", "suddenDeathAmount"],
      collapsible: true,
    },
    {
      id: "options",
      title: "选项配置",
      fieldIds: ["medicalRatio", "hospitalDays", "insuranceDays"],
      collapsible: true,
    },
  ],
}
