import type { QuoterConfig } from "../types"

export const tuanyiConfig: QuoterConfig = {
  id: "group-accident-quoter",
  name: "团体意外险报价器",
  title: "团体意外险报价器",
  description: "用于计算团体意外险保费（单职业类别）",

  fields: [
    {
      id: "companyName",
      name: "投保人",
      label: "投保人",
      type: "text",
      required: false,
      defaultValue: "",
    },
    {
      id: "workType",
      name: "工种选择",
      label: "工种选择",
      type: "select",
      required: true,
      options: [
        { label: "正常工种", value: 1 },
        { label: "正常工种（人力公司投保）", value: 1 },
        { label: "保安、保洁", value: 5 },
        { label: "涉高空作业", value: 1 },
        { label: "涉特种作业", value: 1 },
      ],
      defaultValue: 1,
    },
    {
      id: "suddenDeathAmount",
      name: "猝死保额单列",
      label: "猝死保额单列",
      type: "select",
      required: true,
      options: [
        { label: "猝死保额0万元", value: 0 },
        { label: "猝死保额10万元", value: 10 },
        { label: "猝死保额20万元", value: 20 },
        { label: "猝死保额30万元", value: 30 },
        { label: "猝死保额40万元", value: 40 },
        { label: "猝死保额50万元", value: 50 },
        { label: "猝死保额同主险", value: -1 },
      ],
      defaultValue: 0,
    },
    {
      id: "medicalRatio",
      name: "意外医疗扣除赔付比例",
      label: "意外医疗扣除赔付比例",
      type: "select",
      required: true,
      options: [
        { label: "意外医疗扣除100元后80%比例赔付", value: 1 },
        { label: "意外医疗扣除100元后90%比例赔付", value: 1.2 },
        { label: "意外医疗扣除100元后100%比例赔付", value: 1.4 },
      ],
      defaultValue: 1,
    },
    {
      id: "hospitalDays",
      name: "住院津贴免赔天数",
      label: "住院津贴免赔天数",
      type: "select",
      required: true,
      options: [
        { label: "免赔0天", value: 1.5 },
        { label: "免赔3天", value: 1 },
      ],
      defaultValue: 1.5,
    },
    {
      id: "insuranceDays",
      name: "投保天数",
      label: "投保天数",
      type: "number",
      required: true,
      min: 1,
      max: 365,
      suffix: "天",
      defaultValue: 365,
      tooltip: "不能超过365天",
    },
    {
      id: "occupation",
      name: "职业类别",
      label: "职业类别",
      type: "select",
      required: true,
      options: [
        { label: "一类", value: "class1" },
        { label: "二类", value: "class2" },
        { label: "三类", value: "class3" },
        { label: "四类", value: "class4" },
        { label: "五类", value: "class5" },
        { label: "六类", value: "class6" },
      ],
      defaultValue: "class2",
    },
    {
      id: "peopleCount",
      name: "投保人数",
      label: "投保人数",
      type: "number",
      required: true,
      min: 1,
      max: 100000,
      suffix: "人",
      defaultValue: 10,
      tooltip: "团体投保建议10人以上",
    },
    {
      id: "accidentAmount",
      name: "意外身故/伤残保额",
      label: "意外身故/伤残保额",
      type: "number",
      required: true,
      min: 1,
      max: 100,
      suffix: "万元",
      defaultValue: 60,
      tooltip: "五类、六类职业不超过60万元；四类职业不超过80万元；其他职业不超过100万元",
    },
    {
      id: "medicalAmount",
      name: "附加意外伤害医疗保额",
      label: "附加意外伤害医疗保额",
      type: "number",
      required: true,
      min: 0,
      max: 10,
      suffix: "万元",
      defaultValue: 5,
    },
    {
      id: "hospitalAllowance",
      name: "附加意外伤害住院津贴",
      label: "附加意外伤害住院津贴",
      type: "number",
      required: true,
      min: 0,
      max: 300,
      suffix: "元/天",
      defaultValue: 100,
      tooltip: "不能超过300元/天",
    },
    {
      id: "drivingAmount",
      name: "驾驶或乘坐非营运性质的机动车",
      label: "驾驶或乘坐非营运性质的机动车",
      type: "number",
      required: false,
      min: 0,
      max: 30,
      suffix: "万元",
      defaultValue: 0,
      tooltip: "不能超过30万元",
    },
    {
      id: "busAmount",
      name: "乘坐客运机动车",
      label: "乘坐客运机动车",
      type: "number",
      required: false,
      min: 0,
      max: 30,
      suffix: "万元",
      defaultValue: 0,
      tooltip: "不能超过30万元",
    },
    {
      id: "railAmount",
      name: "乘坐客运轨道交通车辆",
      label: "乘坐客运轨道交通车辆",
      type: "number",
      required: false,
      min: 0,
      max: 200,
      suffix: "万元",
      defaultValue: 0,
      tooltip: "不能超过200万元",
    },
    {
      id: "shipAmount",
      name: "乘坐客运轮船",
      label: "乘坐客运轮船",
      type: "number",
      required: false,
      min: 0,
      max: 100,
      suffix: "万元",
      defaultValue: 0,
      tooltip: "不能超过100万元",
    },
    {
      id: "flightAmount",
      name: "乘坐客运民航班机",
      label: "乘坐客运民航班机",
      type: "number",
      required: false,
      min: 0,
      max: 200,
      suffix: "万元",
      defaultValue: 0,
      tooltip: "不能超过200万元",
    },
    {
      id: "ambulanceFee",
      name: "救护车费用",
      label: "救护车费用",
      type: "number",
      required: false,
      min: 0,
      max: 1,
      suffix: "万元",
      defaultValue: 0,
      tooltip: "不能超过1万元",
    },
  ],

  coefficientTables: [
    {
      id: "occupationCoef",
      name: "职业类别系数表",
      description: "根据职业类别确定各项系数",
      rowKeyName: "职业类别",
      colKeyName: "系数类型",
      data: {
        class1: {
          固定系数: 1.36517857437895,
          身故占比: 0.8,
          伤残占比: 0.2,
          医疗系数: 4.37290786352844,
          住院津贴系数: 0.018119247,
          住院津贴系数折扣: 0.5,
          猝死系数: 0.6,
          人数系数: 1,
        },
        class2: {
          固定系数: 1.63821428925473,
          身故占比: 0.8,
          伤残占比: 0.2,
          医疗系数: 5.24748943623413,
          住院津贴系数: 0.026643096,
          住院津贴系数折扣: 0.5,
          猝死系数: 0.6,
          人数系数: 1,
        },
        class3: {
          固定系数: 2.53149371653327,
          身故占比: 0.7,
          伤残占比: 0.3,
          医疗系数: 8.75206452604031,
          住院津贴系数: 0.038788418,
          住院津贴系数折扣: 0.5,
          猝死系数: 0.6,
          人数系数: 1.25,
        },
        class4: {
          固定系数: 4.15915647700629,
          身故占比: 0.6,
          伤残占比: 0.4,
          医疗系数: 14.5971963162149,
          住院津贴系数: 0.059830028,
          住院津贴系数折扣: 0.5,
          猝死系数: 0.6,
          人数系数: 1.25,
        },
        class5: {
          固定系数: 6.83335000487885,
          身故占比: 0.5,
          伤残占比: 0.5,
          医疗系数: 20.7650513572076,
          住院津贴系数: 0.077520894,
          住院津贴系数折扣: 0.5,
          猝死系数: 0.6,
          人数系数: 1.25,
        },
        class6: {
          固定系数: 10.3312046008418,
          身故占比: 0.5,
          伤残占比: 0.5,
          医疗系数: 29.012589787219,
          住院津贴系数: 0.090272984,
          住院津贴系数折扣: 0.5,
          猝死系数: 0.6,
          人数系数: 1.25,
        },
      },
    },
  ],

  formulas: [
    {
      id: "deathPremium",
      name: "身故保费",
      description: "意外身故保额 × 固定系数 × 身故占比",
      expression: "$accidentAmount * LOOKUP(occupationCoef, $occupation, '固定系数') * LOOKUP(occupationCoef, $occupation, '身故占比')",
      dependencies: ["accidentAmount", "occupation"],
      showInResult: false,
      unit: "元",
    },
    {
      id: "disabilityPremium",
      name: "伤残保费",
      description: "意外伤残保额 × 固定系数 × 伤残占比",
      expression: "$accidentAmount * LOOKUP(occupationCoef, $occupation, '固定系数') * LOOKUP(occupationCoef, $occupation, '伤残占比')",
      dependencies: ["accidentAmount", "occupation"],
      showInResult: false,
      unit: "元",
    },
    {
      id: "medicalDiscountCoef",
      name: "医疗折扣系数",
      description: "根据医疗保额计算折扣系数",
      expression: "IF($medicalAmount > 8, 4.9 / $medicalAmount + 0.2, IF($medicalAmount > 7, 4.2 / $medicalAmount + 0.3, IF($medicalAmount > 6, 2.7 / $medicalAmount + 0.5, IF($medicalAmount > 5, 1.5 / $medicalAmount + 0.7, 1))))",
      dependencies: ["medicalAmount"],
      showInResult: false,
      unit: "",
    },
    {
      id: "medicalPremium",
      name: "医疗保费",
      description: "医疗保额 × 医疗系数 × 医疗折扣系数 × 赔付比例系数",
      expression: "$medicalAmount * LOOKUP(occupationCoef, $occupation, '医疗系数') * @medicalDiscountCoef * $medicalRatio",
      dependencies: ["medicalAmount", "occupation", "medicalDiscountCoef", "medicalRatio"],
      showInResult: false,
      unit: "元",
    },
    {
      id: "hospitalPremium",
      name: "住院津贴保费",
      description: "住院津贴 × 住院津贴系数 × 住院津贴系数折扣 × 免赔天数系数",
      expression: "$hospitalAllowance * LOOKUP(occupationCoef, $occupation, '住院津贴系数') * LOOKUP(occupationCoef, $occupation, '住院津贴系数折扣') * $hospitalDays",
      dependencies: ["hospitalAllowance", "occupation", "hospitalDays"],
      showInResult: false,
      unit: "元",
    },
    {
      id: "suddenDeathCoverage",
      name: "猝死保额",
      description: "根据选择确定猝死保额（-1表示同主险）",
      expression: "IF($suddenDeathAmount == -1, $accidentAmount, $suddenDeathAmount)",
      dependencies: ["suddenDeathAmount", "accidentAmount"],
      showInResult: false,
      unit: "万元",
    },
    {
      id: "suddenDeathPremium",
      name: "猝死保费",
      description: "猝死保额 × 猝死系数 × 猝死系数 × 工种系数",
      expression: "@suddenDeathCoverage * LOOKUP(occupationCoef, $occupation, '猝死系数') * LOOKUP(occupationCoef, $occupation, '猝死系数') * $workType",
      dependencies: ["suddenDeathCoverage", "occupation", "workType"],
      showInResult: false,
      unit: "元",
    },
    {
      id: "insuranceDaysCoef",
      name: "投保天数系数",
      description: "根据投保天数查询对应系数",
      expression: "IF($insuranceDays >= 331, 1, IF($insuranceDays >= 301, 0.95, IF($insuranceDays >= 271, 0.9, IF($insuranceDays >= 241, 0.85, IF($insuranceDays >= 211, 0.8, IF($insuranceDays >= 181, 0.7, IF($insuranceDays >= 151, 0.6, IF($insuranceDays >= 121, 0.5, IF($insuranceDays >= 91, 0.4, IF($insuranceDays >= 61, 0.3, IF($insuranceDays >= 31, 0.2, 0.1)))))))))))",
      dependencies: ["insuranceDays"],
      showInResult: false,
      unit: "",
    },
    {
      id: "riskPremiumTotal",
      name: "风险保费合计",
      description: "所有风险保费之和",
      expression: "@deathPremium + @disabilityPremium + @medicalPremium + @hospitalPremium + @suddenDeathPremium",
      dependencies: ["deathPremium", "disabilityPremium", "medicalPremium", "hospitalPremium", "suddenDeathPremium"],
      showInResult: false,
      unit: "元",
    },
    {
      id: "baseMainPremium",
      name: "主险基准保费",
      description: "（风险保费合计 / 0.6）× 投保天数系数",
      expression: "(@riskPremiumTotal / 0.6) * @insuranceDaysCoef",
      dependencies: ["riskPremiumTotal", "insuranceDaysCoef"],
      showInResult: false,
      unit: "元",
    },
    {
      id: "peopleCountCoef",
      name: "人数系数",
      description: "根据投保人数确定系数",
      expression: "IF($peopleCount < 20, 1.2, IF($peopleCount <= 100, 1, 0.8))",
      dependencies: ["peopleCount"],
      showInResult: false,
      unit: "",
    },
    {
      id: "totalPremiumByOccupation",
      name: "整体保费",
      description: "人数系数 × 投保人数 × 基准保费 × 职业人数系数 × 1.25",
      expression: "@peopleCountCoef * $peopleCount * @baseMainPremium * LOOKUP(occupationCoef, $occupation, '人数系数') * 1.25",
      dependencies: ["peopleCountCoef", "peopleCount", "baseMainPremium", "occupation"],
      showInResult: false,
      unit: "元",
    },
    {
      id: "mainPremiumPerPerson",
      name: "主险保费（每人）",
      description: "整体保费 / 投保人数",
      expression: "ROUND(@totalPremiumByOccupation / $peopleCount, 2)",
      dependencies: ["totalPremiumByOccupation", "peopleCount"],
      showInResult: true,
      unit: "元",
    },
    {
      id: "additionalPremiumPerPerson",
      name: "附加险保费（每人）",
      description: "各附加险保费之和",
      expression: "ROUND(($drivingAmount || 0) * 0.53 + ($busAmount || 0) * 0.23 + ($railAmount || 0) * 0.08 + ($shipAmount || 0) * 0.09 + ($flightAmount || 0) * 0.07 + ($ambulanceFee || 0) * 40, 2)",
      dependencies: ["drivingAmount", "busAmount", "railAmount", "shipAmount", "flightAmount", "ambulanceFee"],
      showInResult: true,
      unit: "元",
    },
    {
      id: "totalPremium",
      name: "总保费",
      description: "(主险保费每人 + 附加险保费每人) × 投保人数",
      expression: "ROUND((@mainPremiumPerPerson + @additionalPremiumPerPerson) * $peopleCount, 2)",
      dependencies: ["mainPremiumPerPerson", "additionalPremiumPerPerson", "peopleCount"],
      showInResult: true,
      unit: "元",
    },
  ],

  sections: [
    {
      id: "common",
      title: "投保报价公共配置",
      fieldIds: ["companyName", "workType", "suddenDeathAmount", "medicalRatio", "hospitalDays", "insuranceDays"],
      collapsible: false,
    },
    {
      id: "basic",
      title: "基础保额信息",
      fieldIds: ["occupation", "peopleCount", "accidentAmount", "medicalAmount", "hospitalAllowance"],
      collapsible: false,
    },
    {
      id: "additional",
      title: "附加保额信息",
      fieldIds: ["drivingAmount", "busAmount", "railAmount", "shipAmount", "flightAmount", "ambulanceFee"],
      collapsible: true,
    },
  ],
}
